[package]
name = "docsmith-model"
version = "0.1.0"
edition = "2024"

[dependencies]
docsmith-base = {version = "0.1.0", path = "../base"}
itertools = "0.14.0"
tinyjson = "2.5.1"

[dev-dependencies]
expect-test = "1.5.1"