import {css} from "@emotion/css";

const contentClass = css`
    padding: 30px 10px;
    scrollbar-width: thin;
`;


export const ContentView = () => {
  return <div class={contentClass}>
    <h1 class="title">Title</h1>
    <h2 class="subtitle">Subtitle</h2>
    
    ContentView
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    <div id="anchor">
      Anchor
    </div>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
    Content<br/>
  </div>;
};
